[mongodb]
server =  "mongodb://localhost/nodeman"

[internal_ca]
issuer_ca_certificate = "internal_ca_certificate.pem"
issuer_ca_private_key = "internal_ca_private_key.pem"
validity_days = 1
min_validity_seconds = 10
max_validity_seconds = 604800
time_skew_seconds = 0

#[step]
#ca_url = "https://localhost:9000"
##ca_fingerprint = "aabb0c2be794316541a6262aa091f4d40533e8436aaf7bd8e8a5e5e42998bd2a"
#ca_fingerprint_file = "root_ca_fingerprint.txt"
#provisioner_name = "test"
#provisioner_private_key ="provisioner_private.json"

[nodes]
nodeman_url = "http://localhost:8080"
aggrec_url = "http://localhost:8080"
domain = "dev.dnstapir.se"
trusted_jwks = "tests/trusted_jwks.json"
mqtt_broker = "mqtts://localhost"

[nodes.mqtt_topics]
tem = "configuration/tem"
pop = "configuration/pop"

[enrollment]
kty = "OKP"
crv = "Ed25519"
alg = "EdDSA"

#[otlp]
#spans_endpoint = "http://localhost:4317"
#metrics_endpoint = "http://localhost:4317"
#insecure = true

[[users]]
username = "username"
password_hash = "$argon2id$v=19$m=65536,t=3,p=4$2UbbvL5YpSjGyeha++HE5g$o8iGuvAgrl0azPFDK79mCYQT10nqIGyU1XLipGwL4rc"
